### ISSUE TITLE
intune downloads office365 apps by delivery optimization?

### ISSUE THREAD

**Issue by hanscees** [ThomasKur/ModernWorkplaceClientCenter#2]
Hi,
we are in the middle of an rollout of 300+ intune-based w10 laptops. We are seeing a large number of rollouts fail. They fail somewhere while downloading office365 app package, especially we think due to network traffic congestion (we rollout 10-15 at the same time.

We do have delivery optimization enabled, but do you know if the office365 app package is downloaded with delivery optimization or not? How can you tell? Can your powershell package help to determine this?
thanks

**Comment by ThomasKur** [comment]
Hi 
O365 Pro Plus supports DO since last summer. So if you are downloading from CDN it should just work. 

Are you using Windows 1903?

**Comment by ThomasKur** [comment]
You can also try the following troubleshooting steps on a device: https://www.petri.com/troubleshoot-windows-update-delivery-optimization

**Comment by hanscees** [comment]
> Hi
> O365 Pro Plus supports DO since last summer. So if you are downloading from CDN it should just work.
> 
> Are you using Windows 1903?

no 1807 I think

**Comment by ThomasKur** [comment]
ok, just because with 1903 more troubleshooting tools would be available, but then the above article should still help. Do you see, that the content is cached?

**Comment by hanscees** [comment]
> ok, just because with 1903 more troubleshooting tools would be available, but then the above article should still help. Do you see, that the content is cached?

I cant read that fast :) I am passing this info to our administrators, thank and if I learn more I will post it. Thanks!

**Comment by ThomasKur** [comment]
Closd to no feedback
