### ISSUE TITLE
Get-DsRegStatus does not support Workplace joined accounts with hybrid join

### ISSUE THREAD

**Issue by MLAR2019** [ThomasKur/ModernWorkplaceClientCenter#4]
Some user have configured a Work Account as a secondary account in those cases some of the object names get duplicated like

DeviceCertificateValidity 
WorkplaceDeviceId 
KeyContainerId 
TpmProtected 
NgcSet 

And others

error

"Cannot add a member with the name "KeyProvider" because a member with that name already exists."

**Comment by ThomasKur** [comment]
Thank you for the feedback. It‘s niw included in the newest version 0.1.15 which is available on PsGallery
